### ISSUE TITLE
unwrap geod_direct

### ISSUE THREAD

**Issue by mcleantom** [geographiclib/geographiclib-c#1]
Hello :)

I was just wondering if there was a way to perform the `geod_direct`calculation so that it unwraps along the meridian and anti-meridian

My test is:
```
TEST(GeodesicCoordinate, forward_antimeridian_unrolls) {
    GEOS x;
    GeodesicCoordinate start(*x.m_xG, 180, 0, 90*DEG_TO_RAD);
    GeodesicCoordinate to = start.forward(10);
    ASSERT_TRUE(to.m_lon > start.m_lon); // We need the coordinates to unroll around the antimeridian
};
```
And the implementation of forward just a wrapper around geod_direct:
```
GeodesicCoordinate GeodesicCoordinate::forward(float NM) {
    double lat, lon, azi;
    geod_direct(&m_GeodGeodesic, m_lat, m_lon, m_azi, NM*NM_TO_M, &lat, &lon, &azi);
    return GeodesicCoordinate(m_GeodGeodesic, lat, lon, azi);
};
```
Thanks for any help!

**Comment by cffk** [comment]
I'm not exactly sure what you're asking; an example of input and expect output would help.  In the meantime, please check [geod_gendirect](https://geographiclib.sourceforge.io/C/doc/geodesic_8h.html#a194f703bfce1939e557bc0d99a0e9c80).  Setting `flags` to `GEOD_UNROLL` might do what you want.

**Comment by mcleantom** [comment]
@cffk Sorry I saw that in the documentation but I am very new to C++ (a few days new) and was a bit confused because of the extra parameters like `ps12` which I didn't need to keep, but now I realize I can just create that variable, pass the pointer into `geod_gendirect` and then ignore its value afterwards:

```cpp
GeodesicCoordinate GeodesicCoordinate::forward(float NM) {
    double lat2, lon2, azi2, s12, m12, M12, M21, S12;
    geod_gendirect(m_GeodGeodesic, m_lat, m_lon, m_azi, GEOD_LONG_UNROLL, NM*NM_TO_M, &lat2, &lon2, &azi2, &s12, &m12, &M12, &M21, &S12);
    return GeodesicCoordinate(m_GeodGeodesic, lon2, lat2, azi2);
};
```
Sorry for the silly question and thank you for your time!

**Comment by cffk** [comment]
This is more complicated than necessary; according to the documentation, you can replace the unneeded pointer arguments by 0:
```c
geod_gendirect(m_GeodGeodesic, m_lat, m_lon, m_azi, GEOD_LONG_UNROLL,
    NM*NM_TO_M, &lat2, &lon2, &azi2, 0, 0, 0, 0, 0);
```

**Comment by mcleantom** [comment]
@cffk  Thanks, that is a lot nicer!

Sorry for the silly questions, again, very new to c++ (and thank you for your time :))

**Comment by cffk** [comment]
For the record, you are using the C version of GeographicLib.  The [C++ library](https://github.com/geographiclib/geographiclib/blob/main/README.md) is substantially more capable.
