### ISSUE TITLE
used defines in Arduino

### ISSUE THREAD

**Issue by dizcza** [geographiclib/geographiclib-c#5]
I cannot use your C version (I don't know if C++ has the same issue but even if it doesn't, I'd like to stick to the C one for cross-platform support) because `B11` is redefined in Arduino.

```
In file included from /home/dizcza/.platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:41,
                 from src/main.cpp:7:
/home/dizcza/.platformio/packages/framework-arduinoespressif32/cores/esp32/binary.h:46:13: error: expected unqualified-id before numeric constant
 #define B11 3
             ^
lib/localize/geodesic.h:113:24: note: in expansion of macro 'B11'
       A1m1, A2m1, A3c, B11, B21, B31, A4, B41;
```

I can simply `#undef B11` as a hotfix but it's always a good idea to prefix such defines with the module name to avoid name collisions in C.

Feel free to close it.

**Comment by cffk** [comment]
I agree: the names of global macros should be prefixed with some string to minimize the potential for conflict.  Please open an issue requesting such a change with the Arduino package in question.

**Comment by dizcza** [comment]
> Please open an issue requesting such a change with the Arduino package in question.

well... I've already opened it here, haven't I? :)

**Comment by cffk** [comment]
No.  This repository has nothing to do with Arduino and contains no file called `binary.h`.  You'll need to figure out the relevant repo and make the request there.  (I starting searching github, and saw some potential candidates, but gave up because I know nothing about the Arduino ecosystem.)

**Comment by dizcza** [comment]
I meant to say these defines should be changed here, not in Arduino (`binary.h`), of course.

**Comment by dizcza** [comment]
Ah, true. They should change it, not you. And they won't change it :)
